[build]
  publish = "."
  command = "echo 'No build step required'"

# Serve sitemap.xml directly
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Serve robots.txt directly
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Specific page redirects for SEO-friendly URLs
[[redirects]]
  from = "/pricing"
  to = "/index.html#pricing"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/index.html#terms"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/index.html#privacy"
  status = 200

[[redirects]]
  from = "/billing"
  to = "/index.html#billing"
  status = 200

[[redirects]]
  from = "/crm"
  to = "/index.html#crm"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html#dashboard"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

# Netlify plugin to install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Environment variables for Stripe and Firebase
# Add these in your Netlify dashboard under Site settings > Environment variables
# STRIPE_SECRET_KEY = "sk_test_..."
# FIREBASE_PROJECT_ID = "your-project-id"
# FIREBASE_CLIENT_EMAIL = "your-service-account@your-project.iam.gserviceaccount.com"
# FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\n..."
# SITE_URL = "https://your-domain.netlify.app"
